AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CobolFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /cobolambda
            Method: get
Outputs:
  CobolFunction: 
    Value: !Ref CobolFunction
